# Conjecture: Real and imaginary parts of eigenvalues
Let $A$ and $B$ be $2 \times 2$ matrices in $\mathbb{Z}_p[i]$ with norm-zero eigenvectors $\vec{u}$ and $\vec{v}$ with corresponding eigenvalues $\lambda_A$, $\mu_A$, $\lambda_B$, $\mu_B$ such that $\text{Re}(\lambda_A)=\text{Re}(\mu_A)=\text{Re}(\lambda_B)=\text{Re}(\mu_B)$ and $\text{Im}(\lambda_A)+\text{Im}(\mu_A)=\text{Im}(\lambda_B)+\text{Im}(\mu_B)$. Then $W(A)=W(B)$.

In [1]:
import numpy as np
from Imports.linalg_Zpi import linalg_Zpi
from Imports.numrange_Zpi import numrange_Zpi

In [2]:
linalg = linalg_Zpi(n=2, p=7)
norm0 = np.load("Imports/norm0/p=7_n=2.npz")["norm0"]
print(norm0)

[[[0.+1.j]
  [2.+3.j]]

 [[0.+1.j]
  [2.+4.j]]

 [[0.+1.j]
  [3.+2.j]]

 [[0.+1.j]
  [3.+5.j]]

 [[0.+1.j]
  [4.+2.j]]

 [[0.+1.j]
  [4.+5.j]]

 [[0.+1.j]
  [5.+3.j]]

 [[0.+1.j]
  [5.+4.j]]]


In [6]:
M = np.array([[complex(0,1), complex(0,1)],
              [complex(2,3), complex(2,4)]])

In [7]:
linalg.inv(M)

array([[5.+3.j, 0.+1.j],
       [2.+3.j, 0.+6.j]])

In [8]:
def norm(v):
    return int(linalg.prod((np.conj(v.transpose()),v)).real.item())

In [11]:
norm(np.array([[complex(5,3)], [complex(0,1)]]))

0

In [12]:
norm(np.array([[complex(2,3)], [complex(0,6)]]))

0

In [16]:
linalg.mult(np.array([[complex(5,3)], [complex(0,1)]]), np.array([[complex(0,1)],[complex(2,3)]]))

In [17]:
linalg.mult(np.array([[complex(5,3)], [complex(0,1)]]), np.array([[complex(0,1)],[complex(2,4)]]))

In [20]:
norm(linalg.sim_a(norm0[0] + norm0[1]))

6

In [21]:
norm0[0]

array([[0.+1.j],
       [2.+3.j]], dtype=complex64)

In [22]:
norm0[1]

array([[0.+1.j],
       [2.+4.j]], dtype=complex64)

In [24]:
linalg.sim_a(norm0[0] + norm0[1])

array([[0.+2.j],
       [4.+0.j]], dtype=complex64)

In [25]:
norm(linalg.sim_a(norm0[0] + norm0[1]))

6